### ISSUE TITLE
configure fails searching qmake-qt4 which does not exist on a recent gentoo

### ISSUE THREAD

**Issue by Das-Sams** [leo-recover/gentoo-openmodelica-overlay#1]
Change the line
`econf --with-omlibrary=no --with-omc=no --with-cppruntime --libdir=/usr/lib`
to
`econf --with-omlibrary=no --with-omc=no --with-cppruntime --libdir=/usr/lib QMAKE=/usr/bin/qmake5`
in both ebuilds and then regenerate the manifests

**Comment by leo-recover** [comment]
Thanks for reporting and for the fix!
Should be fixed in the latest commit.
